artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_path: artifacts/data_ingestion/elliptic
  dataset_name: EllipticBitcoinDataset

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/elliptic
  trained_data_path: artifacts/data_transformation/transformed_data.pt

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.pt
  
model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/transformed_data.pt
  model_path: artifacts/model_training/model.pt
  metric_file_name: artifacts/model_evaluation/metrics.json